# Generated by Django 5.2.1 on 2025-06-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='تحميل صورة المنتج (اختياري)', null=True, upload_to='media/%Y/%m/%d/', verbose_name='صورة المنتج'),
        ),
    ]
