# Generated by Django 5.2.3 on 2025-06-17 01:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف العميل')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='عنوان العميل')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة ائتمان'), ('bank', 'تحويل بنكي')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فاتورة بيع',
                'verbose_name_plural': 'فواتير البيع',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المرتجع')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المسترجع')),
                ('reason', models.TextField(verbose_name='سبب الإرجاع')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة المرتجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='تم التاكيد بواسطة')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='الفاتورة الأصلية')),
            ],
            options={
                'verbose_name': 'مرتجع',
                'verbose_name_plural': 'المرتجعات',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'بند بيع',
                'verbose_name_plural': 'بنود البيع',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المرتجعة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع')),
                ('reason', models.TextField(verbose_name='سبب الإرجاع')),
                ('return_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.return', verbose_name='المرتجع')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleitem', verbose_name='بند البيع')),
            ],
            options={
                'verbose_name': 'بند مرتجع',
                'verbose_name_plural': 'بنود المرتجعات',
            },
        ),
    ]
