# render.yaml - ملف تكوين نشر Render.com

services:
  - type: web
    name: mubark  # استبدل باسم تطبيقك
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: startCommand: gunicorn sales_crm.wsgi:application
  # استبدل your_project باسم مشروعك
    env: python
    plan: free  # الخطة المجانية
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.5  # أو أي إصدار تدعمه Render
      - key: DJANGO_SETTINGS_MODULE
        value: DJANGO_SETTINGS_MODULE  # استبدل your_project باسم مشروعك
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    database:
      name: 'db.sqlite3'  # اختر اسمًا لقاعدة البيانات
      plan: free  # الخطة المجانية

# إعدادات قواعد البيانات (اختياري)
databases:
  - name: 'db.sqlite3'  # نفس الاسم المذكور أعلاه
    plan: free
    databaseName: 'db.sqlite3'
    user: 'db.sqlite3'

buildCommand: |
  if [ ! -f "requirements.txt" ]; then
    echo "Error: Missing requirements.txt!"
    ls -la
    exit 1
  fi
  pip install -r requirements.txt   