# render.yaml - ملف تكوين نشر Render.com

services:
  - type: web
    name: mubark  # استبدل باسم تطبيقك
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn your_project.wsgi:application  # استبدل your_project باسم مشروعك
    env: python
    plan: free  # الخطة المجانية
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.5  # أو أي إصدار تدعمه Render
      - key: DJANGO_SETTINGS_MODULE
        value: your_project.settings  # استبدل your_project باسم مشروعك
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    database:
      name: mbark331122  # اختر اسمًا لقاعدة البيانات
      plan: free  # الخطة المجانية

# إعدادات قواعد البيانات (اختياري)
databases:
  - name: mbark331122  # نفس الاسم المذكور أعلاه
    plan: free
    databaseName: mbark331122
    user: mbark331122

buildCommand: |
  pip install -r requirements.txt
  python manage.py collectstatic --noinput    