# Generated by Django 5.2.3 on 2025-06-17 01:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمدة'), ('received', 'مستلمة'), ('canceled', 'ملغاة')], default='draft', max_length=20, verbose_name='حالة الطلب')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'أجل'), ('transfer', 'تحويل بنكي'), ('apple_pay', 'Apple Pay')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المورد')),
                ('contact', models.CharField(max_length=100, verbose_name='جهة الاتصال')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف المورد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة الإجمالية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='أمر الشراء')),
            ],
            options={
                'verbose_name': 'بند أمر شراء',
                'verbose_name_plural': 'بنود أوامر الشراء',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المرتجع')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المسترجع')),
                ('reason', models.TextField(verbose_name='سبب الإرجاع')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة المرتجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='تم التاكيد بواسطة')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchaseorder', verbose_name='أمر الشراء الأصلي')),
            ],
            options={
                'verbose_name': 'مرتجع شراء',
                'verbose_name_plural': 'مرتجعات المشتريات',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المرتجعة')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع')),
                ('reason', models.TextField(verbose_name='سبب الإرجاع')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.orderitem', verbose_name='بند أمر الشراء')),
                ('return_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn', verbose_name='مرتجع الشراء')),
            ],
            options={
                'verbose_name': 'بند مرتجع شراء',
                'verbose_name_plural': 'بنود مرتجعات المشتريات',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier', verbose_name='المورد'),
        ),
    ]
