# Generated by Django 5.2.3 on 2025-06-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AddField(
            model_name='user',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل السكن'),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'على رأس العمل'), ('vacation', 'في إجازة'), ('resigned', 'مستقيل'), ('terminated', 'مفصول')], default='active', max_length=20, verbose_name='حالة الموظف'),
        ),
        migrations.AddField(
            model_name='user',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إنهاء الخدمة'),
        ),
        migrations.AddField(
            model_name='user',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل النقل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sales', 'بائع'), ('purchases', 'مشتريات'), ('admin', 'مدير النظام'), ('hr', 'موارد بشرية'), ('accountant', 'محاسب')], max_length=20, verbose_name='الدور'),
        ),
    ]
